channels:
    Default:
        channel-tag: '[D]'
        channel-colour: WHITE
        default: true
    HerpChan:
        channel-tag: '[HC]'
        channel-colour: GOLD
        public: false
        allow-colours: true
    DerpChan:
        channel-tag: '[DC]'
        channel-colour: SILVER
        public: true
        allow-colours: false
    Donators:
        channel-tag: '[$]'
        channel-colour: GREEN
        public: false
        allow-colours: true
    Staff:
        channel-tag: '[S]'
        channel-colour: RED
        staff: true