channels:
    enable: true
    limit: -1
logging:
    colouring: true
    debug: []
formatting:
    format: '%tag %prefix%display%suffix: %message'
    variable:
        default: '%var%'
        custom:
            tag: '[%var%]'
            prefix: '[%var%]'
            suffix: '[%var%]'