channels:
    enable: true
    limit: -1
    range: 15
logging:
    chat:
        log: false
        colour: true
    debug: []
formatting:
    chat: '%eptag%prefix%display%suffix: %colour%message'
    emote: '* %prefix%display%suffix %message'
    tag-format:
        default: '%tag%'
        tags:
            chtag: '[%tag%]'
    static-tags:
        plugin: '[TitanChat]'
filtering:
    censor: '*'
    phrases: []
metrics-statistics: true
update-notify: true