#==============================================================#
#                         COLOUR CODES                         #
# &0 (black), &1 (dark blue), &2 (green), &3 (dark aqua),      #
# &4 (red), &5 (purple), &6 (gold), &7 (silver),               #
# &8 (grey), &9 (blue), &a (light green), &b (aqua),           #
# &c (light red), &d (light purple), &e (yellow), &f (white),  #
# &k (magical)                                                 #
# &l (bold), &m (underlined), &n (striked), &o (italic)        #
#==============================================================#

auto-library-update: true
channels:
    enable: true
    tag: ''
    name-display-colour: '&f'
    chat-display-colour: '&f'
    channel-limit: -1
    quick-send:
        enable: true
        key: '@'
    messages:
        join: true
        leave: true
logging:
    colouring: true
broadcast:
    player:
        enable: true
        format: '[&cBroadcast&f] %player: %message'
    server:
        enable: true
        format: '<&4Server&f> %message'
emote:
    player:
        enable: true
        format: '* %player %action'
    server:
        enable: true
        format: '* &4Server &f%action'
whisper:
    player:
        enable: true
        format: '&5%player whispers: %message'
    server:
        enable: true
        format: '&5Server whispers: %message'
formatting:
    use-custom-format: false
    format: "%tag %prefix%player%suffix: %message"
permissions:
    groups:
        user:
            prefix: [&7User&f]
            suffix: ' the &6Member&f'
        admin:
            prefix: [&4Admin&f]
    users:
        NodinChan:
            prefix: [&4Titan&f]
            suffix: ' the &0Dev&f'
debug: none