#==============================================================#
#                         COLOUR CODES                         #
# &0 (black), &1 (dark blue), &2 (green), &3 (dark aqua),      #
# &4 (red), &5 (purple), &6 (gold), &7 (grey), &8 (dark grey), #
# &9 (blue), &a (light green), &b (aqua), &c (light red),      #
# &d (light purple), &e (yellow), &f (white), &k (magic)       #
# &l (bold), &m (underlined), &n (striked), &o (italic)        #
#==============================================================#

channels:
    enable: true
    server:
        tag: ''
        display-colour: '&f'
        topic: ''
    channel-limit: -1
logging:
    colouring: true
    debug: []
chat:
    channel-emote:
        enable: true
        format: '* %player %action'
    player:
        enable: true
        broadcast: '[&cBroadcast&f] %player: %message'
        emote: '* %player %action'
        whisper: '&5%player whispers: %message'
    server:
        enable: true
        broadcast: '<&4Server&f> %message'
        emote: '* &4Server &f%action'
        whisper: '&4Server &5whispers: %message'
formatting:
    format: '%tag %prefix%player%suffix: %message'
    server: '%tag &4Server: %message'
    bracket: '[%var%]'
    variables:
        %tag: '[%var%]'
        %prefix: '[%var%]'
        %suffix: '[%var%]'