use-legacy: false
var:
    static:
        var: "value"
        plugin: "TitanChat"
    format:
        default: "%var%"
        vars:
            prefix: "&f[%var%&f]"
            suffix: "&f%var%&f"
censorship:
    items: []
    censor: "*"
metrics-statistics: true
update-search: false