channels:
    enable: true
    limit: -1
    range: 15
pm:
    display-colour: ''
    format: '%prefix%display%suffix whispers: %colour%message'
logging:
    chat:
        log: false
        colour: true
    debug: []
metrics-statistics: true
formatting:
    format: '%prefix%display%suffix: %colour%message'
    tag-format:
        default: '%tag%'
        tags:
            prefix: '[%tag%]'
filtering:
    censor: '*'
    phrases: []