# Available colour codes:
# &0 (black), &1 (dark blue), &2 (green),
# &3 (sea green), &4 (red), &5 (purple),
# &6 (gold), &7 (silver), &8 (grey),
# &9 (blue), &a (light green), &b (light blue),
# &c (light red), &d (pink), &e (yellow),
# &f (white)

channel-limit: -1
broadcast:
    chat-display-colour: ''
    tag: '[Broadcast]'
channels:
    Default:
        tag: '[D]'
        channel-display-colour: ''
        name-display-colour: ''
        type: default
        global: true
    HerpChan:
        tag: '[HC]'
        channel-display-colour: '&6'
        name-display-colour: '&6'
        type: private
        colour-code: true
    DerpChan:
        tag: '[DC]'
        channel-display-colour: '&7'
        name-display-colour: '&7'
        type: public
        colour-code: false
    MemeChan:
        tag: '[MC]'
        channel-display-colour: '&4'
        name-display-colour: '&4'
        type: password
        password: pass
        global: true
        colour-code: true
    Donators:
        tag: '$'
        channel-display-colour: '&2'
        name-display-colour: '&2'
        type: private
        colour-code: true
        format: '&f[&2%tag&f] %gprefix%player%gsuffix: %message'
    Staff:
        tag: '&f[&4S&f]'
        channel-display-colour: '&4'
        name-display-colour: '&4'
        type: staff
formatting:
    use-built-in: true
    format: "%tag %pprefix%player%psuffix: %message"
channel-messages:
    join: true
    leave: true