tag: '[D]'
display-colour: '&f'
loader-type: 'Standard'
channel-type: 'default'
aliases: [d]
topic: 'Welcome to the default channel'
setting:
    colouring: false
    range: 'channel'
    radius: 15
    whitelist: false
password: ''
format: ''
admins: []
blacklist: []
followers: []
whitelist: []