tag: '[L]'
display-colour: '&2'
loader-type: 'Standard'
channel-type: 'none'
aliases: [l]
topic: 'Welcome to the local channel || Chat is sent to players within a radius of 15 blocks'
setting:
    colouring: true
    range: 'local'
    radius: 15
    whitelist: false
password: ''
format: ''
admins: []
blacklist: []
followers: []
whitelist: []