# Available colour codes:
# &0 (black), &1 (dark blue), &2 (green),
# &3 (sea green), &4 (red), &5 (purple),
# &6 (gold), &7 (silver), &8 (grey),
# &9 (blue), &a (light green), &b (light blue),
# &c (light red), &d (pink), &e (yellow),
# &f (white)

channel-limit: -1
local:
    chat-display-colour: '&e'
    tag: '[L]'
    radius: 15
broadcast:
    chat-display-colour: ''
    tag: '[Broadcast]'
channels:
    Default:
        tag: '[D]'
        channel-display-colour: ''
        name-display-colour: ''
        status: default
        global: true
    HerpChan:
        tag: '[HC]'
        channel-display-colour: '&6'
        name-display-colour: '&6'
        status: private
        colour-code: true
    DerpChan:
        tag: '[DC]'
        channel-display-colour: '&7'
        name-display-colour: '&7'
        status: public
        colour-code: false
    MemeChan:
        tag: '[MC]'
        channel-display-colour: '&4'
        name-display-colour: '&4'
        status: password
        password: pass
        global: true
        colour-code: true
    Donators:
        tag: '$'
        channel-display-colour: '&2'
        name-display-colour: '&2'
        status: private
        colour-code: true
        format: '&f[&2%tag&f] %prefix%player%suffix: %message'
    Staff:
        tag: '&f[&4S&f]'
        channel-display-colour: '&4'
        name-display-colour: '&4'
        status: staff
formatting:
    use-built-in: true
    format: "%tag %prefix%player%suffix: %message"
filter:
    enable: true
    censor: '*'
    phrases:
    - filter