name: TitanChat
version: 2.0.1
author: NodinChan
main: com.titankingdoms.nodinchan.titanchat.TitanChat
depend: [Vault]
commands:
    titanchat:
        description: TitanChat Commands
        aliases: tc
        usage: /<command> [action] [argument]
permissions:
    TitanChat.admin:
        description: Access to everything
        default: op
        children:
            TitanChat.create: true
            TitanChat.delete: true
            TitanChat.broadcast: true
            TitanChat.silence: true
            TitanChat.force: true
            TitanChat.access.*: true
            TitanChat.ban.*: true
            TitanChat.kick.*: true
            TitanChat.rank.*: true
            TitanChat.colours: true
            TitanChat.voice: true
            TitanChat.admin.spawn: true
    TitanChat.mod:
        description: Access to moderation perms, has voice
        default: op
        children:
            TitanChat.ban.*: true
            TitanChat.kick.*: true
            TitanChat.mute: true
            TitanChat.voice: true
    TitanChat.silence:
        description: Access to silence
        default: op
        children:
            TitanChat.mute: true
    TitanChat.admin.spawn:
        description: Enforces Admin to join Staff Channel as Default
        default: op