name: TitanChat
version: 1.0
author: NodinChan
main: com.titankingdoms.nodinchan.titanchat.TitanChat
solftdepend: [Vault, PermissionsEx, bPermissions]
commands:
    titanchat:
        description: TitanChat Commands
        aliases: tc
        usage: /<command> [action] [argument]
permissions:
    TitanChat.admin:
        description: Access to everything
        default: op
        children:
            TitanChat.create: true
            TitanChat.delete: true
            TitanChat.broadcast: true
            TitanChat.silence: true
            TitanChat.force: true
            TitanChat.access.*: true
            TitanChat.ban.*: true
            TitanChat.kick.*: true
            TitanChat.rank.*: true
            TitanChat.allowcolours: true
            TitanChat.voice: true
    TitanChat.silence:
        description: Access to silence
        default: op
        children:
            TitanChat.mute: true